### ISSUE TITLE
issue with hello world program

### ISSUE THREAD

**Issue by simone-romiti** [MolSSI-Education/parallel-programming#6]
I can't run the example program in https://education.molssi.org/parallel-programming/setup.html
I followed the steps but I get the following:

```
$ mpiexec -n 4 python -c "from mpi4py import MPI;print(MPI.COMM_WORLD.Get_size())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[55181,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

I have already tried installing `mpich` with `sudo apt install mpich`.
I'm working on a laptop with Ubuntu 22.04.1 LTS installed.

**Comment by simone-romiti** [comment]
It seems the origin of the issue has to do with the `conda` environment. 
It works if using a regular `pip` installation with slight modifications,

`pip install numpy mpi4py mpi4py-mpich cmake intel-openmp compilers`

**Comment by taylor-a-barnes** [comment]
Thanks very much for this report; glad you got it working.  At some point, I'm hopeful that we will have the opportunity to add instructions for running the tests within a containerized environment, so that there is less chance of running into environment-specific issues.  As you've observed, mpi4py can sometimes be tricky to get set up properly.
